### ISSUE TITLE
Aggregate and collect logs for rpch services

### ISSUE THREAD

**Issue by sitilge** [Rpc-h/applications-platform#10]
# Description

The goal of this epic is to create the infraestructure needed to be able to aggregate logs from different services and their instances and collect them so they can be used by the developers to analyze the behaviour of the applications.

# Related issues

- [x] #30
- [x] Decide on the setup and architecture of the toolset chosen
- [x] Implement the infrastructure code to deploy the toolset on the Stage environment
- [x] Integrate the toolset with Authelia
- [x] Configure the initial setup for the tool by code
- [x] Adapt entry nodes to forward logs to the tool
- [x] Adapt exit nodes to forward logs to the tool
- [x] Adapt discovery platform to forward logs to the tool
- [x] Adapt funding service to forward logs to the tool
- [x] Create dashboard on the tool to see the most relevant logs from an environment (stage, production)
- [x] Create documentation and setup a meeting to the stakeholders to explain about the usage of the tool
- [x] Deploy the tool in the production environment
- [x] Create users if needed for the tool in production

# Definition of done
- [x] Stakeholders are able to analyse logs from the running services in a single tool
- [x] The tool is integrated with a SSO.
- [x] Stakeholders know how to use the tool

**Comment by nionis** [comment]
@sitilge please expand issue to an epic
