### ISSUE TITLE
NIRP v1

### ISSUE THREAD

**Issue by tolbrino** [Rpc-h/applications-platform#46]
Deployment of a single-location proxy for all RPC request which multiplexes requests over multiple RPC providers.

# Requirements

- proxy is deployed in a single location in Europe
- proxy must be over provisioned to compensate for usage spikes
- proxy must be able to scale vertically (more resources)
- proxy must be configured to use several RPC providers as targets
- proxy endpoint is served over HTTPS
- reconfiguration must be possible
- non-functioning RPC provider endpoints must be disabled for a period of time

# Design

NIRP is implemented as a haproxy deployment which proxies incoming Ethereum RPC requests over multiple RPC provider endpoints. The RPC provider endpoints may be distributed globally while the haproxy deployment is in a single location and can be reached through a single DNS name over HTTPS.

Each RPC provider endpoint satisfies the following criteria:

- reachable via HTTPS url and implements Ethereum RPC API
- supports some capacity of calls
- fails when capacity is reached

The configuration of RPC provider endpoints is weighted to account for different capacities among the endpoints.

If an endpoint fails, e.g. returns multiple non-200 HTTP responses, it is taken out of the rotation and only added back in if multiple HTTP requests succeed again.

The configuration, and therefore proxying, has 2 layers:

1. Networks: Starts with Gnosis Chain only, must be extendable to include other networks.
2. Endpoint: These are network specific. There is a 1-n relationship between networks and endpoints.

Therefore, the proxy exposes a separate url for each network.

# Out of Scope

- globally distributed deployment to optimise overall latency
- automatic RPC endpoint selection based on recent RPC endpoint latency
- per-method RPC endpoint selection

# Definition of Done

- [ ] NIRP is deployed and reachable
- [ ] logs can be viewed in Grafana, handled via Loki
- [ ] metrics are visible in a Grafana dashboard
